--- #Create VPC, IGW, Subnets & Sec Groups
- hosts: localhost
  gather_facts: no
  vars:
    ami_id = "ami-0cff7528ff583bf9a"
  module_defaults:
    group/aws:
      region: us-east-1
  tasks:
    - name: create launch template
      community.aws.ec2_launch_template:
        template_name: ans-launch-template
        tags:
          Name: ig-ans-launch-temp
        image_id: "{{ ami_id }}"
        key_name: development
        instance_type: t3.nano
        security_group_ids:
          - "{{ ans_nginx_servers.group_id }}"
          - "{{ postgres_tag.group_id }}"
          - "{{ ans_ig_secmgrtag.group_id }}"
        network_interfaces:
          associate_public_ip_address: yes
          description: net interface for ans-autoscaled instances
        user_data: "{{ lookup('file', 'ec2_asgscript.sh') }}"
        state: present
