---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      region: us-east-1
  tasks:
  - name: create ans-postgres-secret
    community.aws.aws_secret:
      name: ans-ig-postgres
      description: secret for postgres password
      secret_type: 'string'
      secret: "cpsc-4970-m5project"
      tags:
        Name: ans-postgres-secret
      state: present
    register: ans_postgres_secret
  - name: create ans-ig-secret
    community.aws.aws_secret:
      name: ans-ig-image_gallery
      description: secret for image_gallery password
      secret_type: 'string'
      secret: "cpsc-4970-an$dbP4ssw0rd"
      tags:
        Name: ans-image-gallery-secret
      state: present
    register: ans_imagegallery_secret
  - name: create flask secret
    community.aws.aws_secret:
      name: ans-flask-secret
      description: secret for flask session secret
      secret_type: 'string'
      secret: "asd15q&_(*^[iuj^)*&lkn"
      tags:
        Name: ans-image-gallery-secret
      state: present
    register: ans_flask_secret
