---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-0cff7528ff583bf9a"  
  module_defaults:
    group/aws:
      region: us-east-1
  tasks:
    - name: create IAM server role
      community.aws.iam_role:
        name: ans-image-gallery-server-role
        description: Role needed for Ansible instances to perform actions
        state: present
      register: ans_iam_role
    - name: create s3 policy
      community.aws.iam_policy:
        policy_name: ans-image-gallery-s3-policy
        iam_type: role
        iam_name: "{{ ans_iam_role.role_name }}"
        policy_json: "{{ lookup('file', 's3_policy.json')"
    - name: create sec mgr policy
      community.aws.iam_policy:
        policy_name: ans-image-gallery-secmgr
        iam_type: role
        iam_name: "{{ ans_iam_role.role_name }}"
        policy_json: "{{ lookup('file', 'secmgr_policy.json')"
    - name: create flask session policy
      community.aws.iam_policy:
        policy_name: ans-image-gallery-flask-access
        iam_type: role
        iam_name: "{{ ans_iam_role.role_name }}"
        policy_json: "{{ lookup('file', 'flask_policy.json')"
    - name: create rds policy
      community.aws.iam_policy:
        policy_name: ans-image-gallery-rds-access
        iam_type: role
        iam_name: "{{ ans_iam_role.role_name }}"
        policy_json: "{{ lookup('file', 'rds_policy.json')"
    - name: create launch template
      community.aws.ec2_launch_template:
        template_name: ans-launch-template
        tags:
          Name: ig-ans-launch-temp
        image_id: "{{ ami_id }}"
        key_name: development
        instance_type: t3.nano
        security_group_ids:
          - "{{ ans_nginx_servers.group_id }}"
          - "{{ postgrestag_sg.group_id }}"
          - "{{ ans_ig_secmgrtag.group_id }}"
        network_interfaces:
          - description: net interface for ans-autoscaled instances
            associate_public_ip_address: yes
            groups:
             - "{{ ans_nginx_servers.group_id }}"
             - "{{ postgrestag_sg.group_id }}"
             - "{{ ans_ig_secmgrtag.group_id }}"
        user_data: "{{ lookup('file', 'ec2_asgscript.sh') | b64encode }}"
        state: present
